name: CI/CD Multi-Docker

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Cache npm
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # 4. Instalar dependências
      - name: Instalar dependências
        run: npm install
        working-directory: ./client

      # 5. Rodar testes
      - name: Rodar testes
        run: npm test -- --coverage
        working-directory: ./client

      # 6. Build imagens Docker
      - name: Build imagens Docker
        if: github.event_name == 'push'
        run: |
          docker build -t absjrdev/multi-client:latest ./client
          docker build -t absjrdev/multi-nginx:latest ./nginx
          docker build -t absjrdev/multi-server:latest ./server
          docker build -t absjrdev/multi-worker:latest ./worker

      # 7. Login Docker Hub
      - name: Login no Docker Hub
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 8. Push das imagens
      - name: Push das imagens
        if: github.event_name == 'push'
        run: |
          docker push absjrdev/multi-client:latest
          docker push absjrdev/multi-nginx:latest
          docker push absjrdev/multi-server:latest
          docker push absjrdev/multi-worker:latest

      # 9. Gerar deploy.zip (IMPORTANTÍSSIMO)
      - name: Gerar pacote de deploy
        if: github.event_name == 'push'
        run: zip -r deploy.zip docker-compose.yml

      # 10. Deploy AWS Elastic Beanstalk
      # - name: Deploy to Elastic Beanstalk
      # if: github.event_name == 'push'
      # uses: einaregilsson/beanstalk-deploy@v21
      # with:
      #   aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   application_name: multi-docker
      #   environment_name: Multi-Docker-env
      #   region: sa-east-1 
      #   version_label: ${{ github.sha }}-${{ github.run_id }} 
      #   deployment_package: deploy.zip
